version: 0.2

phases:
  install:
    commands:
      - echo installing nginx
      - sudo apt update -y
      - sudo apt install nginx -y
  build:
    commands
      - echo build started on `date`
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo configuring nginx
artifacts:
  files:
    - /var/www/html/index.html