version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt update -y
      - apt install -y nginx
  build:
    commands:
      - echo "Build started on `date`"
      - mkdir -p output
      - cp index.html output/
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - output/index.html
